use anyhow::{Context, Result};
use serde::Deserialize;
use std::fs;
use std::path::Path;
use std::process::Command;

#[derive(Deserialize, Debug)]
pub struct DownloadScript {
    /// Relative path from the output directory, e.g. "Artist Name" or "Show Title/S01"
    pub path: String,
    /// Shell commands: one `wget` line per file
    pub content: String,
}

pub fn write_scripts(
    scripts: Vec<DownloadScript>,
    base_dir: &Path,
    dry_run: bool,
) -> Result<Vec<std::path::PathBuf>> {
    let mut created = Vec::new();

    for script in scripts {
        let dir = base_dir.join(&script.path);
        let script_path = dir.join("download.sh");

        if script_path.exists() {
            eprintln!("  skip  {} (already exists)", script_path.display());
            continue;
        }

        let content = format!(
            "#!/usr/bin/env bash\nset -e\n\n# Generated by debrid-collector\n# {}\n\n{}\n",
            script.path,
            script.content.trim()
        );

        if dry_run {
            println!("--- {} ---", script_path.display());
            println!("{content}");
            continue;
        }

        fs::create_dir_all(&dir)
            .with_context(|| format!("failed to create {}", dir.display()))?;
        fs::write(&script_path, &content)
            .with_context(|| format!("failed to write {}", script_path.display()))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = fs::metadata(&script_path)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&script_path, perms)?;
        }

        eprintln!("  wrote {}", script_path.display());
        created.push(script_path);
    }

    Ok(created)
}

pub fn run_script(path: &Path) -> Result<()> {
    eprintln!("running {}...", path.display());
    let status = Command::new("bash")
        .arg(path)
        .current_dir(path.parent().unwrap_or(Path::new(".")))
        .status()
        .with_context(|| format!("failed to run {}", path.display()))?;

    if !status.success() {
        anyhow::bail!("{} exited with {status}", path.display());
    }
    Ok(())
}
